services:
  - type: web
    name: me-v2-backend
    env: python
    buildCommand: pip install --upgrade pip && pip install --no-cache-dir -r requirements-simple.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app --host 0.0.0.0 --port $PORT 
    # Environment variables
    envVars:
      - key: DATABASE_URL # Supabase
        sync: false  # Don't sync between environments
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: REDIRECT_URI
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: FRONTEND_URL  # Vercel
        sync: false
      - key: ALLOWED_ORIGINS  # CORS - will include Vercel URL
        sync: false