"""Add intensity_score to SessionExercise

Revision ID: 219c52365ae6
Revises: 4b9714029d7e
Create Date: 2024-10-04 21:52:55.799301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '219c52365ae6'
down_revision: Union[str, None] = '4b9714029d7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_exercises', sa.Column('total_intensity_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_exercises', 'total_intensity_score')
    # ### end Alembic commands ###
