"""Add user_id and is_global to Exercise model

Revision ID: 4b9714029d7e
Revises: 8962b11d78c0
Create Date: 2024-10-02 21:51:57.524822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b9714029d7e'
down_revision: Union[str, None] = '8962b11d78c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('exercises', sa.Column('is_global', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_exercises_exercise_id'), 'exercises', ['exercise_id'], unique=False)
    op.create_foreign_key(None, 'exercises', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'workout_sets', 'session_exercises', ['session_exercise_id'], ['session_exercise_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workout_sets', type_='foreignkey')
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.drop_index(op.f('ix_exercises_exercise_id'), table_name='exercises')
    op.drop_column('exercises', 'is_global')
    op.drop_column('exercises', 'user_id')
    # ### end Alembic commands ###
