"""Add historical logging support - system settings, grace periods, and audit fields

Revision ID: a474debf6e34
Revises: a950a0850061
Create Date: 2025-11-13 20:10:04.184230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a474debf6e34'
down_revision: Union[str, None] = 'a950a0850061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create system_settings table if it doesn't exist
    # (Some dev databases may already have this table from testing)
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)

    if 'system_settings' not in inspector.get_table_names():
        op.create_table('system_settings',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('setting_key', sa.String(), nullable=False),
            sa.Column('setting_value', sa.String(), nullable=False),
            sa.Column('description', sa.String(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.Column('updated_by', sa.Integer(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
        op.create_index(op.f('ix_system_settings_setting_key'), 'system_settings', ['setting_key'], unique=True)

    op.add_column('user_activities', sa.Column('logged_by_admin', sa.Boolean(), nullable=True))
    op.add_column('user_activities', sa.Column('admin_user_id', sa.Integer(), nullable=True))
    op.add_column('user_activities', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'user_activities', 'users', ['admin_user_id'], ['id'])
    op.add_column('user_challenges', sa.Column('failed_date', sa.Date(), nullable=True))
    op.add_column('user_challenges', sa.Column('grace_period_used', sa.Boolean(), nullable=True))
    op.add_column('user_challenges', sa.Column('grace_period_date', sa.Date(), nullable=True))
    op.add_column('weight_tracking', sa.Column('logged_by_admin', sa.Boolean(), nullable=True))
    op.add_column('weight_tracking', sa.Column('admin_user_id', sa.Integer(), nullable=True))
    op.add_column('weight_tracking', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'weight_tracking', 'users', ['admin_user_id'], ['id'])
    op.add_column('workout_sessions', sa.Column('logged_by_admin', sa.Boolean(), nullable=True))
    op.add_column('workout_sessions', sa.Column('admin_user_id', sa.Integer(), nullable=True))
    op.add_column('workout_sessions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'workout_sessions', 'users', ['admin_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workout_sessions', type_='foreignkey')
    op.drop_column('workout_sessions', 'created_at')
    op.drop_column('workout_sessions', 'admin_user_id')
    op.drop_column('workout_sessions', 'logged_by_admin')
    op.drop_constraint(None, 'weight_tracking', type_='foreignkey')
    op.drop_column('weight_tracking', 'created_at')
    op.drop_column('weight_tracking', 'admin_user_id')
    op.drop_column('weight_tracking', 'logged_by_admin')
    op.drop_column('user_challenges', 'grace_period_date')
    op.drop_column('user_challenges', 'grace_period_used')
    op.drop_column('user_challenges', 'failed_date')
    op.drop_constraint(None, 'user_activities', type_='foreignkey')
    op.drop_column('user_activities', 'created_at')
    op.drop_column('user_activities', 'admin_user_id')
    op.drop_column('user_activities', 'logged_by_admin')

    # Drop system_settings table
    op.drop_index(op.f('ix_system_settings_setting_key'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
