"""add user roles

Revision ID: a950a0850061
Revises: 
Create Date: 2025-08-27 18:19:35.133943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a950a0850061'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create the enum type first
    userrole_enum = sa.Enum('USER', 'ADMIN', 'MODERATOR', name='userrole')
    userrole_enum.create(op.get_bind(), checkfirst=True)
    
    # Add the column as nullable first
    op.add_column('users', sa.Column('role', userrole_enum, nullable=True))
    
    # Set default value for existing users
    op.execute("UPDATE users SET role = 'USER' WHERE role IS NULL")
    
    # Now make the column not nullable
    op.alter_column('users', 'role', nullable=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # Drop the enum type
    op.execute("DROP TYPE IF EXISTS userrole")
    # ### end Alembic commands ###
