"""Add CASCADE delete to WorkoutSessionExercise

Revision ID: ea3db47a7b0a
Revises: 46d2f6c38e51
Create Date: 2024-03-24 20:54:45.471061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea3db47a7b0a'
down_revision: Union[str, None] = '46d2f6c38e51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('workout_session_exercises_program_exercise_id_fkey', 'workout_session_exercises', type_='foreignkey')
    op.create_foreign_key(None, 'workout_session_exercises', 'workout_program_exercises', ['program_exercise_id'], ['program_exercise_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workout_session_exercises', type_='foreignkey')
    op.create_foreign_key('workout_session_exercises_program_exercise_id_fkey', 'workout_session_exercises', 'workout_program_exercises', ['program_exercise_id'], ['program_exercise_id'])
    # ### end Alembic commands ###
