
# Data for ExerciseCategory
exercise_categories = [
    {'name': 'Strength'},
]

# Data for ExerciseMuscleGroup
exercise_muscle_groups = [
    {'name': 'Chest'},
    {'name': 'Back'},
    {'name': 'Shoulders'},
    {'name': 'Arms'},
    {'name': 'Legs'},
    {'name': 'Core'},
    {'name': 'Full Body'},
]

# Data for ExerciseEquipment
exercise_equipments = [
    {'name': 'Bodyweight'},
    {'name': 'Free Weights'},
    {'name': 'Machines'},
    {'name': 'Cables'},
    {'name': 'Resistance Bands'},
    {'name': 'Other'},
]

# Data for ExerciseDifficultyLevel
exercise_difficulty_levels = [
    {'level': 'Beginner'},
    {'level': 'Intermediate'},
    {'level': 'Advanced'},
]

# Data for ExerciseType
exercise_types = [
    {'type': 'Compound'},
    {'type': 'Isolation'},
]

# Popular exercises list (partial)
popular_exercises = [
    {
        "name": "Bench Press",
        "description": "Lie on a bench and press a barbell up from your chest.",
        "category": "Strength",
        "muscle_group": "Chest",
        "equipment": "Free Weights",
        "difficulty": "Intermediate",
        "exercise_type": "Compound",
        "primary_muscles": "Pectoralis Major",
        "secondary_muscles": "Triceps, Shoulders",
        "instructions": "Lie back on a flat bench with a barbell at chest level. Grip the bar slightly wider than shoulder-width and press upwards.",
        "media_url": None,
    },
    {
        "name": "Push-up",
        "description": "Raise and lower your body using your arms while in a plank position.",
        "category": "Strength",
        "muscle_group": "Chest",
        "equipment": "Bodyweight",
        "difficulty": "Beginner",
        "exercise_type": "Compound",
        "primary_muscles": "Pectoralis Major",
        "secondary_muscles": "Triceps, Shoulders, Core",
        "instructions": "Start in a plank position with hands under shoulders. Lower your body until your chest nearly touches the floor and push back up.",
        "media_url": None,
    },
    {
        "name": "Squat",
        "description": "Lower your hips from a standing position and then stand back up.",
        "category": "Strength",
        "muscle_group": "Legs",
        "equipment": "Free Weights",
        "difficulty": "Intermediate",
        "exercise_type": "Compound",
        "primary_muscles": "Quadriceps",
        "secondary_muscles": "Glutes, Hamstrings, Core",
        "instructions": "Stand with feet shoulder-width apart. Bend your knees and hips to lower your body as if sitting back into a chair. Keep your chest up and back straight. Push through your heels to return to standing.",
        "media_url": None,
    },
    {
        "name": "Deadlift",
        "description": "Lift a barbell from the ground to hip level and then lower it back down.",
        "category": "Strength",
        "muscle_group": "Back",
        "equipment": "Free Weights",
        "difficulty": "Advanced",
        "exercise_type": "Compound",
        "primary_muscles": "Hamstrings, Glutes",
        "secondary_muscles": "Lower Back, Trapezius, Forearms",
        "instructions": "Stand with feet hip-width apart, barbell over mid-foot. Bend at the hips and knees, grip the bar just outside your legs. Lift by extending hips and knees, keeping the bar close to your body.",
        "media_url": None,
    },
    {
        "name": "Overhead Press",
        "description": "Press a barbell or dumbbells from shoulder level to overhead.",
        "category": "Strength",
        "muscle_group": "Shoulders",
        "equipment": "Free Weights",
        "difficulty": "Intermediate",
        "exercise_type": "Compound",
        "primary_muscles": "Deltoids",
        "secondary_muscles": "Triceps, Upper Chest, Core",
        "instructions": "Stand with feet shoulder-width apart. Hold the barbell at shoulder level with palms facing forward. Press the bar overhead until arms are fully extended. Lower back to shoulder level.",
        "media_url": None,
    },
    {
        "name": "Pull-up",
        "description": "Hang from a bar and pull your body upward until your chin is above the bar.",
        "category": "Strength",
        "muscle_group": "Back",
        "equipment": "Other",
        "difficulty": "Advanced",
        "exercise_type": "Compound",
        "primary_muscles": "Latissimus Dorsi",
        "secondary_muscles": "Biceps, Forearms, Upper Back",
        "instructions": "Grip the pull-up bar with palms facing away. Hang with arms fully extended. Pull your body up until your chin clears the bar, then lower back down with control.",
        "media_url": None,
    },
    {
        "name": "Bent Over Row",
        "description": "Bend at the waist and row a barbell or dumbbells to your torso.",
        "category": "Strength",
        "muscle_group": "Back",
        "equipment": "Free Weights",
        "difficulty": "Intermediate",
        "exercise_type": "Compound",
        "primary_muscles": "Latissimus Dorsi",
        "secondary_muscles": "Biceps, Rear Deltoids, Lower Back",
        "instructions": "Hold a barbell with an overhand grip. Bend knees slightly and bend at the waist, keeping back straight. Pull the barbell to your lower ribcage, then lower it back down.",
        "media_url": None,
    },
    {
        "name": "Lunge",
        "description": "Step forward into a lunge position and then return to standing.",
        "category": "Strength",
        "muscle_group": "Legs",
        "equipment": "Free Weights",
        "difficulty": "Intermediate",
        "exercise_type": "Compound",
        "primary_muscles": "Quadriceps, Glutes",
        "secondary_muscles": "Hamstrings, Calves, Core",
        "instructions": "Stand upright, step forward with one leg, lowering hips until both knees are bent at 90 degrees. Push back to the starting position and repeat with the other leg.",
        "media_url": None,
    },
    {
        "name": "Dumbbell Shoulder Press",
        "description": "Press dumbbells from shoulder height to overhead.",
        "category": "Strength",
        "muscle_group": "Shoulders",
        "equipment": "Free Weights",
        "difficulty": "Intermediate",
        "exercise_type": "Compound",
        "primary_muscles": "Deltoids",
        "secondary_muscles": "Triceps, Upper Chest, Core",
        "instructions": "Sit or stand with dumbbells at shoulder height, palms facing forward. Press the weights overhead until arms are fully extended. Lower back to shoulder height.",
        "media_url": None,
    },
    {
        "name": "Bicep Curl",
        "description": "Curl a dumbbell or barbell towards your shoulder.",
        "category": "Strength",
        "muscle_group": "Arms",
        "equipment": "Free Weights",
        "difficulty": "Beginner",
        "exercise_type": "Isolation",
        "primary_muscles": "Biceps Brachii",
        "secondary_muscles": "Forearms",
        "instructions": "Stand with feet shoulder-width apart, holding a dumbbell in each hand. Curl the weights towards your shoulders while keeping elbows stationary. Lower back down with control.",
        "media_url": None,
    },
    {
        "name": "Tricep Dip",
        "description": "Lower and raise your body using your triceps while on parallel bars or a bench.",
        "category": "Strength",
        "muscle_group": "Arms",
        "equipment": "Other",
        "difficulty": "Intermediate",
        "exercise_type": "Compound",
        "primary_muscles": "Triceps Brachii",
        "secondary_muscles": "Chest, Shoulders",
        "instructions": "Position your hands shoulder-width apart on a bench or parallel bars. Lower your body by bending elbows until upper arms are parallel to the floor. Push back up to the starting position.",
        "media_url": None,
    },
    {
        "name": "Leg Press",
        "description": "Push a weighted platform away using your legs.",
        "category": "Strength",
        "muscle_group": "Legs",
        "equipment": "Machines",
        "difficulty": "Intermediate",
        "exercise_type": "Compound",
        "primary_muscles": "Quadriceps",
        "secondary_muscles": "Glutes, Hamstrings, Calves",
        "instructions": "Sit on the leg press machine with feet shoulder-width apart on the platform. Push the platform away by extending your knees and hips. Slowly return to the starting position.",
        "media_url": None,
    },
    {
        "name": "Romanian Deadlift",
        "description": "Perform a deadlift focusing on the hamstrings by keeping legs slightly bent.",
        "category": "Strength",
        "muscle_group": "Legs",
        "equipment": "Free Weights",
        "difficulty": "Intermediate",
        "exercise_type": "Compound",
        "primary_muscles": "Hamstrings",
        "secondary_muscles": "Glutes, Lower Back",
        "instructions": "Stand with feet hip-width apart holding a barbell. Keep knees slightly bent, hinge at the hips to lower the barbell while keeping it close to your legs. Return to the starting position by extending hips.",
        "media_url": None,
    },
    {
        "name": "Front Squat",
        "description": "Perform a squat with the barbell held at the front of your shoulders.",
        "category": "Strength",
        "muscle_group": "Legs",
        "equipment": "Free Weights",
        "difficulty": "Advanced",
        "exercise_type": "Compound",
        "primary_muscles": "Quadriceps",
        "secondary_muscles": "Glutes, Hamstrings, Core",
        "instructions": "Place the barbell on the front of your shoulders, crossing arms to secure it or using a clean grip. Squat down by bending knees and hips, keeping torso upright. Push through heels to return to standing.",
        "media_url": None,
    },
    {
        "name": "Bulgarian Split Squat",
        "description": "Perform a single-leg squat with the rear foot elevated on a bench.",
        "category": "Strength",
        "muscle_group": "Legs",
        "equipment": "Free Weights",
        "difficulty": "Intermediate",
        "exercise_type": "Compound",
        "primary_muscles": "Quadriceps, Glutes",
        "secondary_muscles": "Hamstrings, Calves, Core",
        "instructions": "Stand a few feet in front of a bench. Place the rear foot on the bench. Lower your body by bending the front knee until the thigh is parallel to the floor. Push through the front heel to return to standing.",
        "media_url": None,
    },
    {
        "name": "Cable Row",
        "description": "Pull a weighted cable towards your torso while seated.",
        "category": "Strength",
        "muscle_group": "Back",
        "equipment": "Cables",
        "difficulty": "Intermediate",
        "exercise_type": "Compound",
        "primary_muscles": "Latissimus Dorsi",
        "secondary_muscles": "Biceps, Rear Deltoids, Core",
        "instructions": "Sit at a cable row machine with feet planted. Grip the handle, keep your back straight, and pull the handle towards your torso by squeezing your shoulder blades together. Slowly extend your arms back to the starting position.",
        "media_url": None,
    },
    {
        "name": "Lat Pulldown",
        "description": "Pull a bar down towards your chest while seated.",
        "category": "Strength",
        "muscle_group": "Back",
        "equipment": "Cables",
        "difficulty": "Intermediate",
        "exercise_type": "Compound",
        "primary_muscles": "Latissimus Dorsi",
        "secondary_muscles": "Biceps, Rear Deltoids, Core",
        "instructions": "Sit at a lat pulldown machine and grip the bar wider than shoulder-width. Pull the bar down to your chest while leaning back slightly. Slowly return the bar to the starting position.",
        "media_url": None,
    },
    {
        "name": "Dumbbell Bench Press",
        "description": "Press dumbbells up from your chest while lying on a bench.",
        "category": "Strength",
        "muscle_group": "Chest",
        "equipment": "Free Weights",
        "difficulty": "Intermediate",
        "exercise_type": "Compound",
        "primary_muscles": "Pectoralis Major",
        "secondary_muscles": "Triceps, Shoulders",
        "instructions": "Lie back on a flat bench holding a dumbbell in each hand at chest level. Press the dumbbells upward until arms are fully extended. Lower them back to the starting position.",
        "media_url": None,
    },
    {
        "name": "Incline Bench Press",
        "description": "Press a barbell or dumbbells upward from an inclined bench.",
        "category": "Strength",
        "muscle_group": "Chest",
        "equipment": "Free Weights",
        "difficulty": "Intermediate",
        "exercise_type": "Compound",
        "primary_muscles": "Chest",
        "secondary_muscles": "Triceps, Shoulders",
        "instructions": "Set an incline bench at 30-45 degrees. Lie back holding a barbell or dumbbells at chest level. Press the weight upward until arms are fully extended, then lower back down.",
        "media_url": None,
    },
    {
        "name": "Seated Military Press",
        "description": "Press a barbell overhead while seated.",
        "category": "Strength",
        "muscle_group": "Shoulders",
        "equipment": "Free Weights",
        "difficulty": "Intermediate",
        "exercise_type": "Compound",
        "primary_muscles": "Deltoids",
        "secondary_muscles": "Triceps, Upper Chest, Core",
        "instructions": "Sit on a bench with back support holding a barbell at shoulder level with palms facing forward. Press the barbell overhead until arms are fully extended. Lower back to shoulder level.",
        "media_url": None,
    },
    {
        "name": "Upright Row",
        "description": "Lift a barbell or dumbbells vertically to chest level.",
        "category": "Strength",
        "muscle_group": "Shoulders",
        "equipment": "Free Weights",
        "difficulty": "Intermediate",
        "exercise_type": "Compound",
        "primary_muscles": "Deltoids",
        "secondary_muscles": "Trapezius, Biceps",
        "instructions": "Stand with feet shoulder-width apart holding a barbell or dumbbells in front of you. Pull the weights straight up to chest level by lifting your elbows upward. Lower back down with control.",
        "media_url": None,
    },
    {
        "name": "Shrug",
        "description": "Elevate your shoulders while holding dumbbells or a barbell.",
        "category": "Strength",
        "muscle_group": "Back",
        "equipment": "Free Weights",
        "difficulty": "Beginner",
        "exercise_type": "Isolation",
        "primary_muscles": "Trapezius",
        "secondary_muscles": "Neck",
        "instructions": "Stand upright holding dumbbells or a barbell at your sides. Shrug your shoulders upward as high as possible. Hold briefly and then lower back down.",
        "media_url": None,
    },
    {
        "name": "Calf Raise",
        "description": "Raise your heels off the ground to work the calf muscles.",
        "category": "Strength",
        "muscle_group": "Legs",
        "equipment": "Bodyweight",
        "difficulty": "Beginner",
        "exercise_type": "Isolation",
        "primary_muscles": "Gastrocnemius, Soleus",
        "secondary_muscles": "Calves",
        "instructions": "Stand with feet shoulder-width apart. Raise your heels off the ground by pushing through the balls of your feet. Hold briefly at the top and then lower back down.",
        "media_url": None,
    },
    {
        "name": "Glute Bridge",
        "description": "Lift your hips off the ground to engage the glutes and hamstrings.",
        "category": "Strength",
        "muscle_group": "Legs",
        "equipment": "Bodyweight",
        "difficulty": "Beginner",
        "exercise_type": "Compound",
        "primary_muscles": "Glutes",
        "secondary_muscles": "Hamstrings, Lower Back, Core",
        "instructions": "Lie on your back with knees bent and feet flat on the floor. Lift your hips toward the ceiling by squeezing your glutes. Hold at the top and then lower back down.",
        "media_url": None,
    },
    {
        "name": "Hip Thrust",
        "description": "Thrust your hips upward while your upper back is supported on a bench.",
        "category": "Strength",
        "muscle_group": "Legs",
        "equipment": "Free Weights",
        "difficulty": "Intermediate",
        "exercise_type": "Compound",
        "primary_muscles": "Glutes",
        "secondary_muscles": "Hamstrings, Lower Back",
        "instructions": "Sit on the ground with your upper back against a bench and a barbell over your hips. Drive through your heels to lift your hips upward, squeezing your glutes at the top. Lower back down with control.",
        "media_url": None,
    },
    {
        "name": "Abdominal Crunch",
        "description": "Curl your torso towards your thighs to engage the abdominal muscles.",
        "category": "Strength",
        "muscle_group": "Core",
        "equipment": "Bodyweight",
        "difficulty": "Beginner",
        "exercise_type": "Isolation",
        "primary_muscles": "Rectus Abdominis",
        "secondary_muscles": "Obliques",
        "instructions": "Lie on your back with knees bent and feet flat on the floor. Place your hands behind your head or across your chest. Curl your torso upward towards your thighs, then lower back down.",
        "media_url": None,
    },
    {
        "name": "Plank",
        "description": "Hold a push-up position to engage the core and stabilize muscles.",
        "category": "Strength",
        "muscle_group": "Core",
        "equipment": "Bodyweight",
        "difficulty": "Beginner",
        "exercise_type": "Isolation",
        "primary_muscles": "Core",
        "secondary_muscles": "Shoulders, Glutes, Legs",
        "instructions": "Start in a forearm plank position with elbows under shoulders and body in a straight line. Hold the position, keeping your core tight and avoiding sagging or arching your back.",
        "media_url": None,
    },
    {
        "name": "Russian Twist",
        "description": "Twist your torso from side to side while holding a weight.",
        "category": "Strength",
        "muscle_group": "Core",
        "equipment": "Free Weights",
        "difficulty": "Intermediate",
        "exercise_type": "Isolation",
        "primary_muscles": "Obliques",
        "secondary_muscles": "Rectus Abdominis, Transverse Abdominis",
        "instructions": "Sit on the floor with knees bent and feet lifted slightly off the ground. Hold a dumbbell with both hands. Twist your torso to the right, then to the left to complete one rep.",
        "media_url": None,
    },
    {
        "name": "Hanging Leg Raise",
        "description": "Lift your legs while hanging from a pull-up bar to target the core.",
        "category": "Strength",
        "muscle_group": "Core",
        "equipment": "Other",
        "difficulty": "Advanced",
        "exercise_type": "Isolation",
        "primary_muscles": "Lower Abs",
        "secondary_muscles": "Hip Flexors",
        "instructions": "Hang from a pull-up bar with arms fully extended. Keeping legs straight, lift them upward until they are parallel to the floor. Slowly lower them back down with control.",
        "media_url": None,
    },
    {
        "name": "Farmer's Walk",
        "description": "Walk while holding heavy weights in each hand to build grip and core strength.",
        "category": "Strength",
        "muscle_group": "Full Body",
        "equipment": "Free Weights",
        "difficulty": "Intermediate",
        "exercise_type": "Compound",
        "primary_muscles": "Grip, Core",
        "secondary_muscles": "Legs, Shoulders, Back",
        "instructions": "Hold a heavy dumbbell in each hand with arms at your sides. Walk forward for a set distance or time while maintaining good posture.",
        "media_url": None,
    },
    {
        "name": "Kettlebell Swing",
        "description": "Swing a kettlebell between your legs and up to shoulder height using hip thrusts.",
        "category": "Strength",
        "muscle_group": "Full Body",
        "equipment": "Other",
        "difficulty": "Intermediate",
        "exercise_type": "Compound",
        "primary_muscles": "Hamstrings, Glutes",
        "secondary_muscles": "Lower Back, Shoulders, Core",
        "instructions": "Stand with feet shoulder-width apart holding a kettlebell with both hands. Hinge at the hips to swing the kettlebell between your legs, then thrust your hips forward to swing it up to shoulder height. Let the kettlebell swing back down and repeat.",
        "media_url": None,
    },
    {
        "name": "Clean and Press",
        "description": "Lift a barbell from the floor to the shoulders and then press it overhead.",
        "category": "Strength",
        "muscle_group": "Full Body",
        "equipment": "Free Weights",
        "difficulty": "Advanced",
        "exercise_type": "Compound",
        "primary_muscles": "Hamstrings, Glutes, Shoulders",
        "secondary_muscles": "Triceps, Back, Core",
        "instructions": "Stand with feet hip-width apart holding a barbell. Clean the barbell to shoulder height by extending hips and knees. From the shoulders, press the barbell overhead until arms are fully extended. Lower back to shoulders, then to the ground.",
        "media_url": None,
    },
    {
        "name": "Snatch",
        "description": "Lift a barbell from the ground to overhead in one continuous motion.",
        "category": "Strength",
        "muscle_group": "Full Body",
        "equipment": "Free Weights",
        "difficulty": "Advanced",
        "exercise_type": "Compound",
        "primary_muscles": "Hamstrings, Glutes, Shoulders",
        "secondary_muscles": "Back, Core, Arms",
        "instructions": "Stand with feet hip-width apart holding a barbell. Explosively lift the barbell by extending hips and pulling it overhead in one motion. Catch the barbell overhead with arms fully extended. Lower it back to the ground with control.",
        "media_url": None,
    },
    {
        "name": "T-Bar Row",
        "description": "Row a barbell fixed at one end to target the back muscles.",
        "category": "Strength",
        "muscle_group": "Back",
        "equipment": "Machines",
        "difficulty": "Intermediate",
        "exercise_type": "Compound",
        "primary_muscles": "Latissimus Dorsi",
        "secondary_muscles": "Biceps, Rear Deltoids, Core",
        "instructions": "Stand over the T-bar row machine with feet shoulder-width apart. Bend at the hips and knees, grasp the handles. Pull the bar towards your torso by squeezing your shoulder blades together. Lower it back down with control.",
        "media_url": None,
    },
    {
        "name": "Chest Fly",
        "description": "Bring dumbbells together in a wide arc to target the chest muscles.",
        "category": "Strength",
        "muscle_group": "Chest",
        "equipment": "Free Weights",
        "difficulty": "Intermediate",
        "exercise_type": "Isolation",
        "primary_muscles": "Pectoralis Major",
        "secondary_muscles": "Shoulders",
        "instructions": "Lie on a flat bench holding a dumbbell in each hand above your chest with arms slightly bent. Lower the dumbbells out to the sides in a wide arc until you feel a stretch in your chest. Bring them back to the starting position.",
        "media_url": None,
    },
    {
        "name": "Cable Crossover",
        "description": "Pull cables from high pulleys down and across the body to target the chest.",
        "category": "Strength",
        "muscle_group": "Chest",
        "equipment": "Cables",
        "difficulty": "Intermediate",
        "exercise_type": "Isolation",
        "primary_muscles": "Pectoralis Major",
        "secondary_muscles": "Shoulders, Triceps",
        "instructions": "Stand in the center of a cable crossover machine with pulleys set above shoulder height. Grab the handles with arms outstretched. Pull the handles downward and across your body until your hands meet in front of you. Return to the starting position with control.",
        "media_url": None,
    },
    {
        "name": "Single-Arm Row",
        "description": "Row a dumbbell towards your torso one arm at a time to target the back.",
        "category": "Strength",
        "muscle_group": "Back",
        "equipment": "Free Weights",
        "difficulty": "Intermediate",
        "exercise_type": "Compound",
        "primary_muscles": "Latissimus Dorsi",
        "secondary_muscles": "Biceps, Rear Deltoids, Core",
        "instructions": "Place one knee and hand on a bench for support. Hold a dumbbell in the other hand with arm extended. Pull the dumbbell towards your torso by bending the elbow and squeezing your back muscles. Lower it back down with control.",
        "media_url": None,
    },
    {
        "name": "Machine Press",
        "description": "Press the weight away using a chest press machine.",
        "category": "Strength",
        "muscle_group": "Chest",
        "equipment": "Machines",
        "difficulty": "Beginner",
        "exercise_type": "Compound",
        "primary_muscles": "Pectoralis Major",
        "secondary_muscles": "Triceps, Shoulders",
        "instructions": "Sit on the chest press machine with feet flat on the floor. Grip the handles and press them forward until arms are fully extended. Slowly return to the starting position.",
        "media_url": None,
    },
    {
        "name": "Hack Squat",
        "description": "Perform a squat using a hack squat machine to target the legs.",
        "category": "Strength",
        "muscle_group": "Legs",
        "equipment": "Machines",
        "difficulty": "Intermediate",
        "exercise_type": "Compound",
        "primary_muscles": "Quadriceps",
        "secondary_muscles": "Glutes, Hamstrings",
        "instructions": "Position your feet shoulder-width apart on the platform of the hack squat machine. Lower your body by bending your knees and hips until thighs are parallel to the floor. Push through your heels to return to the starting position.",
        "media_url": None,
    },
    {
        "name": "Sumo Deadlift",
        "description": "Perform a deadlift with a wider stance to emphasize the inner thighs and glutes.",
        "category": "Strength",
        "muscle_group": "Legs",
        "equipment": "Free Weights",
        "difficulty": "Advanced",
        "exercise_type": "Compound",
        "primary_muscles": "Hamstrings, Glutes",
        "secondary_muscles": "Legs, Lower Back, Forearms",
        "instructions": "Stand with feet wider than shoulder-width apart, toes pointed outward. Grip the barbell with hands inside your knees. Lift the bar by extending hips and knees, keeping the bar close to your body. Lower it back down with control.",
        "media_url": None,
    },
    {
        "name": "Step-up",
        "description": "Step onto a raised platform with one leg at a time to work the legs and glutes.",
        "category": "Strength",
        "muscle_group": "Legs",
        "equipment": "Free Weights",
        "difficulty": "Intermediate",
        "exercise_type": "Compound",
        "primary_muscles": "Quadriceps, Glutes",
        "secondary_muscles": "Hamstrings, Calves, Core",
        "instructions": "Stand in front of a bench or step holding dumbbells at your sides. Step onto the platform with one foot, pressing through the heel to lift your body up. Step back down and repeat with the other leg.",
        "media_url": None,
    },
    {
        "name": "Medicine Ball Slam",
        "description": "Lift a medicine ball overhead and slam it down forcefully to engage the entire body.",
        "category": "Strength",
        "muscle_group": "Full Body",
        "equipment": "Other",
        "difficulty": "Intermediate",
        "exercise_type": "Compound",
        "primary_muscles": "Core, Shoulders",
        "secondary_muscles": "Legs, Back, Arms",
        "instructions": "Stand with feet shoulder-width apart holding a medicine ball overhead. Slam the ball down to the ground as hard as possible by engaging your core and using your arms. Catch the ball on the rebound and repeat.",
        "media_url": None,
    },
    {
        "name": "Dumbbell Fly",
        "description": "Perform a chest fly using dumbbells to isolate the chest muscles.",
        "category": "Strength",
        "muscle_group": "Chest",
        "equipment": "Free Weights",
        "difficulty": "Intermediate",
        "exercise_type": "Isolation",
        "primary_muscles": "Pectoralis Major",
        "secondary_muscles": "Shoulders",
        "instructions": "Lie on a flat bench holding a dumbbell in each hand above your chest with a slight bend in your elbows. Lower the dumbbells out to the sides in a wide arc until you feel a stretch in your chest. Bring them back to the starting position.",
        "media_url": None,
    },
    {
        "name": "Concentration Curl",
        "description": "Perform a bicep curl focusing on one arm at a time while seated.",
        "category": "Strength",
        "muscle_group": "Arms",
        "equipment": "Free Weights",
        "difficulty": "Beginner",
        "exercise_type": "Isolation",
        "primary_muscles": "Biceps Brachii",
        "secondary_muscles": "Forearms",
        "instructions": "Sit on a bench with legs apart. Hold a dumbbell in one hand and rest your elbow on the inside of your thigh. Curl the dumbbell towards your shoulder, squeezing the bicep. Lower it back down with control.",
        "media_url": None,
    },
    {
        "name": "Hammer Curl",
        "description": "Perform a bicep curl with palms facing each other to target the brachialis.",
        "category": "Strength",
        "muscle_group": "Arms",
        "equipment": "Free Weights",
        "difficulty": "Beginner",
        "exercise_type": "Isolation",
        "primary_muscles": "Brachialis, Biceps Brachii",
        "secondary_muscles": "Forearms",
        "instructions": "Stand with feet shoulder-width apart holding a dumbbell in each hand with palms facing each other. Curl the weights towards your shoulders while keeping your palms facing each other. Lower them back down with control.",
        "media_url": None,
    },
    {
        "name": "Tricep Extension",
        "description": "Extend your arms overhead to target the triceps.",
        "category": "Strength",
        "muscle_group": "Arms",
        "equipment": "Free Weights",
        "difficulty": "Intermediate",
        "exercise_type": "Isolation",
        "primary_muscles": "Triceps Brachii",
        "secondary_muscles": "Forearms",
        "instructions": "Hold a dumbbell with both hands overhead, arms fully extended. Lower the dumbbell behind your head by bending the elbows. Extend your arms back to the starting position.",
        "media_url": None,
    },
    {
        "name": "Skull Crusher",
        "description": "Lower a barbell or dumbbells towards your forehead to work the triceps.",
        "category": "Strength",
        "muscle_group": "Arms",
        "equipment": "Free Weights",
        "difficulty": "Intermediate",
        "exercise_type": "Isolation",
        "primary_muscles": "Triceps Brachii",
        "secondary_muscles": "Forearms",
        "instructions": "Lie on a bench holding a barbell or dumbbells with arms extended above your chest. Lower the weight towards your forehead by bending the elbows. Extend your arms back to the starting position.",
        "media_url": None,
    },
    {
        "name": "Push Press",
        "description": "Use a slight dip of the knees to help press a barbell overhead.",
        "category": "Strength",
        "muscle_group": "Shoulders",
        "equipment": "Free Weights",
        "difficulty": "Advanced",
        "exercise_type": "Compound",
        "primary_muscles": "Deltoids",
        "secondary_muscles": "Triceps, Legs, Core",
        "instructions": "Stand with feet shoulder-width apart holding a barbell at shoulder level. Perform a slight dip by bending the knees, then explosively extend the legs while pressing the barbell overhead. Lower the bar back to shoulder level.",
        "media_url": None,
    },
    {
        "name": "Zercher Squat",
        "description": "Perform a squat holding the barbell in the crooks of your elbows.",
        "category": "Strength",
        "muscle_group": "Legs",
        "equipment": "Free Weights",
        "difficulty": "Advanced",
        "exercise_type": "Compound",
        "primary_muscles": "Quadriceps, Glutes",
        "secondary_muscles": "Hamstrings, Core, Upper Back",
        "instructions": "Hold the barbell in the crooks of your elbows with arms bent. Stand with feet shoulder-width apart. Squat down by bending knees and hips, keeping chest up. Push through your heels to return to standing.",
        "media_url": None,
    },
    {
        "name": "Pistol Squat",
        "description": "Perform a single-leg squat with the non-working leg extended forward.",
        "category": "Strength",
        "muscle_group": "Legs",
        "equipment": "Bodyweight",
        "difficulty": "Advanced",
        "exercise_type": "Compound",
        "primary_muscles": "Quadriceps, Glutes",
        "secondary_muscles": "Hamstrings, Calves, Core",
        "instructions": "Stand on one leg with the other leg extended forward. Lower your body into a squat by bending the standing knee while keeping the other leg extended. Push through the heel to return to standing.",
        "media_url": None,
    },
    {
        "name": "Kettlebell Goblet Squat",
        "description": "Hold a kettlebell close to your chest while performing a squat.",
        "category": "Strength",
        "muscle_group": "Legs",
        "equipment": "Free Weights",
        "difficulty": "Beginner",
        "exercise_type": "Compound",
        "primary_muscles": "Quadriceps, Glutes",
        "secondary_muscles": "Hamstrings, Core",
        "instructions": "Hold a kettlebell by the horns close to your chest. Stand with feet shoulder-width apart. Perform a squat by bending knees and hips, keeping chest up and back straight. Push through heels to return to standing.",
        "media_url": None,
    },
    {
        "name": "Cable Tricep Pushdown",
        "description": "Push the cable down to extend the triceps.",
        "category": "Strength",
        "muscle_group": "Arms",
        "equipment": "Cables",
        "difficulty": "Intermediate",
        "exercise_type": "Isolation",
        "primary_muscles": "Triceps Brachii",
        "secondary_muscles": "Forearms",
        "instructions": "Stand facing the cable machine with a straight bar attached to the high pulley. Grip the bar with palms facing down. Push the bar down by extending your elbows until your arms are fully extended. Slowly return to the starting position.",
        "media_url": None,
    },
    {
        "name": "Cable Bicep Curl",
        "description": "Curl the cable towards your shoulder to target the biceps.",
        "category": "Strength",
        "muscle_group": "Arms",
        "equipment": "Cables",
        "difficulty": "Intermediate",
        "exercise_type": "Isolation",
        "primary_muscles": "Biceps Brachii",
        "secondary_muscles": "Forearms",
        "instructions": "Stand facing the cable machine with a straight bar attached to the low pulley. Grip the bar with palms facing up. Curl the bar towards your shoulders while keeping your elbows stationary. Slowly lower the bar back to the starting position.",
        "media_url": None,
    },
    {
        "name": "Face Pull",
        "description": "Pull the rope towards your face to engage the rear deltoids and upper back.",
        "category": "Strength",
        "muscle_group": "Shoulders",
        "equipment": "Cables",
        "difficulty": "Intermediate",
        "exercise_type": "Isolation",
        "primary_muscles": "Rear Deltoids",
        "secondary_muscles": "Upper Back, Trapezius",
        "instructions": "Attach a rope to the high pulley of a cable machine. Stand facing the machine and grasp the rope with both hands. Pull the rope towards your face, separating your hands as you do so. Squeeze your shoulder blades together at the peak contraction. Slowly return to the starting position.",
        "media_url": None,
    },
    {
        "name": "Reverse Fly",
        "description": "Perform a reverse fly using dumbbells to target the rear deltoids and upper back.",
        "category": "Strength",
        "muscle_group": "Back",
        "equipment": "Free Weights",
        "difficulty": "Intermediate",
        "exercise_type": "Isolation",
        "primary_muscles": "Rear Deltoids",
        "secondary_muscles": "Upper Back, Trapezius",
        "instructions": "Hold a dumbbell in each hand with palms facing each other. Bend your knees slightly and hinge at the hips, keeping your back flat. With a slight bend in your elbows, raise the dumbbells out to the sides until they are at shoulder level. Squeeze your shoulder blades together at the top. Slowly lower the weights back to the starting position.",
        "media_url": None,
    },
    {
        "name": "Cable Woodchop",
        "description": "Twist your torso while pulling the cable diagonally to engage the obliques and core.",
        "category": "Strength",
        "muscle_group": "Core",
        "equipment": "Cables",
        "difficulty": "Intermediate",
        "exercise_type": "Isolation",
        "primary_muscles": "Obliques",
        "secondary_muscles": "Rectus Abdominis, Transverse Abdominis",
        "instructions": "Attach a handle to a high pulley cable machine. Stand with feet shoulder-width apart. Grip the handle with both hands and extend your arms overhead. Pull the handle down and across your body in a diagonal motion, rotating your torso as you do so. Return to the starting position with control.",
        "media_url": None,
    },
    {
        "name": "Resistance Band Pull Apart",
        "description": "Pull the resistance band apart to strengthen the upper back and shoulders.",
        "category": "Strength",
        "muscle_group": "Back",
        "equipment": "Resistance Bands",
        "difficulty": "Beginner",
        "exercise_type": "Isolation",
        "primary_muscles": "Rear Deltoids",
        "secondary_muscles": "Upper Back, Trapezius",
        "instructions": "Hold a resistance band with both hands at shoulder width in front of you. Keep your arms straight and pull the band apart by squeezing your shoulder blades together. Hold briefly at the peak contraction, then slowly return to the starting position.",
        "media_url": None,
    },
    {
        "name": "Preacher Curl",
        "description": "Perform a bicep curl using a preacher bench to isolate the biceps.",
        "category": "Strength",
        "muscle_group": "Arms",
        "equipment": "Free Weights",
        "difficulty": "Intermediate",
        "exercise_type": "Isolation",
        "primary_muscles": "Biceps Brachii",
        "secondary_muscles": "Forearms",
        "instructions": "Set up a preacher bench and sit down with your upper arms resting on the bench pad. Hold a barbell or dumbbells with an underhand grip. Curl the weight towards your shoulders, squeezing your biceps at the top. Slowly lower the weight back to the starting position.",
        "media_url": None,
    },
    {
        "name": "Face Pull with Rope",
        "description": "Use a rope attachment to perform face pulls for the upper back and rear delts.",
        "category": "Strength",
        "muscle_group": "Shoulders",
        "equipment": "Cables",
        "difficulty": "Intermediate",
        "exercise_type": "Isolation",
        "primary_muscles": "Rear Deltoids",
        "secondary_muscles": "Upper Back, Trapezius",
        "instructions": "Attach a rope to a high pulley cable machine. Stand facing the machine and grab the rope with both hands, thumbs pointing backward. Pull the rope towards your face, separating your hands as you do so. Squeeze your shoulder blades together at the peak contraction. Slowly return to the starting position.",
        "media_url": None,
    },
    {
        "name": "Single-Leg Deadlift",
        "description": "Perform a deadlift on one leg to target the hamstrings and improve balance.",
        "category": "Strength",
        "muscle_group": "Legs",
        "equipment": "Free Weights",
        "difficulty": "Intermediate",
        "exercise_type": "Compound",
        "primary_muscles": "Hamstrings, Glutes",
        "secondary_muscles": "Lower Back, Core",
        "instructions": "Stand on one leg holding a dumbbell or kettlebell in the opposite hand. Keeping a slight bend in your standing knee, hinge at the hips to lower the weight towards the ground while extending the free leg behind you. Maintain a flat back throughout the movement. Return to the starting position by contracting your hamstrings and glutes.",
        "media_url": None,
    }
    # Add more exercises here
]

from sqlalchemy.orm import Session
from .models import workout_model
from sqlalchemy.exc import IntegrityError

def populate_lookup_table(db: Session, model, data):
    for item in data:
        if not db.query(model).filter_by(**item).first():
            db_item = model(**item)
            db.add(db_item)
    db.commit()

def populate_lookup_tables(db: Session):
    populate_lookup_table(db, workout_model.ExerciseCategory, exercise_categories)
    populate_lookup_table(db, workout_model.ExerciseMuscleGroup, exercise_muscle_groups)
    populate_lookup_table(db, workout_model.ExerciseEquipment, exercise_equipments)
    populate_lookup_table(db, workout_model.ExerciseDifficultyLevel, exercise_difficulty_levels)
    populate_lookup_table(db, workout_model.ExerciseType, exercise_types)

def populate_exercises(db: Session):
    for exercise in popular_exercises:
        # Get the foreign key IDs
        category = db.query(workout_model.ExerciseCategory).filter_by(name=exercise['category']).first()
        muscle_group = db.query(workout_model.ExerciseMuscleGroup).filter_by(name=exercise['muscle_group']).first()
        equipment = db.query(workout_model.ExerciseEquipment).filter_by(name=exercise['equipment']).first()
        difficulty = db.query(workout_model.ExerciseDifficultyLevel).filter_by(level=exercise['difficulty']).first()
        ex_type = db.query(workout_model.ExerciseType).filter_by(type=exercise['exercise_type']).first()

        # Check if exercise already exists
        existing_exercise = db.query(workout_model.Exercise).filter_by(name=exercise['name']).first()
        if existing_exercise:
            existing_exercise.is_global = True
            existing_exercise.user_id = None
            continue  # Skip if exercise already exists

        # Create the exercise
        db_exercise = workout_model.Exercise(
            name=exercise['name'],
            description=exercise['description'],
            instructions=exercise['instructions'],
            primary_muscles=exercise['primary_muscles'],
            secondary_muscles=exercise['secondary_muscles'],
            media_url=exercise['media_url'],
            category_id=category.id,
            muscle_group_id=muscle_group.id,
            equipment_id=equipment.id,
            difficulty_level_id=difficulty.id,
            exercise_type_id=ex_type.id,
            is_global=True,
            user_id=None
        )
        db.add(db_exercise)

    db.commit()

def init_exercise_library(db: Session):
    try:
        populate_lookup_tables(db)
        update_existing_exercises_to_global(db)
        populate_exercises(db)
        print("Exercise library initialized successfully.")
    except IntegrityError:
        db.rollback()
        print("Exercise library already initialized. Use update_exercise_library() to update.")
    except Exception as e:
        db.rollback()
        print(f"Error initializing exercise library: {str(e)}")

def update_exercise_library(db: Session):
    try:
        populate_lookup_tables(db)
        update_existing_exercises_to_global(db)
        populate_exercises(db)
        print("Exercise library updated successfully.")
    except Exception as e:
        db.rollback()
        print(f"Error updating exercise library: {str(e)}")

def update_existing_exercises_to_global(db: Session):
    db.query(workout_model.Exercise).update({
        workout_model.Exercise.is_global: True,
        workout_model.Exercise.user_id: None
    })
    db.commit()
    print("All existing exercises updated to global status.")